# Generated by Django 3.2.2 on 2021-05-10 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20210510_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creted_at',
            new_name='created_at',
        ),
    ]
